app_movie:
    resource: "@AppBundle/Resources/config/routing/movie.yml"
    prefix:   /movie

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

hidden_animate:
    path:     /bzzz
    defaults: { _controller: AppBundle:Default:animate }