services:
#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app_movie_generator:
        class:        AppBundle\Services\MovieGenerator
        # arguments:    ["@service_container", 'star']