AppBundle\Entity\Movie:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MovieRepository
    id:
        id:
            type: string
            id: true
    fields:
        title:
            type: string
            length: 255
        year:
            type: string
            length: 4
        summary:
            type: text
        cover:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
