AppBundle\Entity\Quote:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\QuoteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        film:
            type: string
            length: 255
        author:
            type: string
            length: 255
        quote:
            type: text
    lifecycleCallbacks: {  }
